FROM golang:1.19.3-alpine AS builder
WORKDIR /app
COPY role/aiml_mitlab/main.go main.go
COPY go.mod .
COPY go.sum .
RUN go mod tidy && go build -o main main.go

FROM alpine:3.16.3
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 4503
CMD [ "./main" ]



