FROM golang:1.19.3-alpine AS builder
WORKDIR /app
ADD role/model_storage/main.go main.go
ADD go.mod .
ADD go.sum .
RUN go mod tidy && go build -o main main.go

FROM alpine:3.16.3
WORKDIR /app
COPY models /app/models
COPY --from=builder /app/main .
EXPOSE 4504
CMD [ "./main" ]